# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_R=3.3.2
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "afEioIh6CoR5zR6fepRti0vuew0c1UB4FucFuJyWYmtr2goaSLjXYpkc+QONX/JIb6MJQNtPZBdQiJccqnDqltNT7Yh7/8zeaM9nlyItfe1i/qlAmqtWsvtM7U8DxQBmZ5gqYowsGpj5Zj8OvLNZ+DjEg4EAXBuekm3W8/67Pe+IdPHYxPEOOfX24TlyOb3t3DM+cbdZVURKHNcOY0O6+A6IdLM4v9A7wPN03YQ55IowqPK0ng06rFkPoFWZp+hsf+IkRFdya1bkSDxURSKdiZeIsQgmHRoNdLqca7fXUP39HTgvYCQXtJu3peOgXel9NhGCjNTvTaXb06D0RGke658l+QkkX/dx8cqnoJYTPW6lcHVH8H1PZb629b4kMjJgM3snjOLul/p8PTTdN3/sGwWTZV4WsOktLb1BiZDVsEv3SY4g77+ms22JGQ5tpIoW1BSrLpWp5Ds2Z/96FoImDbNkD8w4xtmEed7th1H1qAT9E8VubjNkFFHijL/PC/bL726eEp1nnWnjvQpyU7MO4yOpRVwfunWFR5jqeyFKukh7ysnWvXnGZqwZDipiX8MpY7l40fWKg54qQDttRClutDVAiLQzhwteivl2LgXBNJ3+6/odUcSAAFSh/RNLaJSCLCogqiE8Y51glMdjqXA347sMHHykwUjjXxUJRd2yHK0="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
