travis:
  secure:
    BINSTAR_TOKEN: qPdIcs0DBhanMnyhp28NxIxYhg0jUdtqc00ot3e+bHZ9m/gjfVhSQ/NwYdPJ9t+TU8bibdKFYhcnbZ6griGWzxoCFzgN6BfZMlDnP6SxaTF67mHjt2OGzsKlxMmHFjMKZRqTXC4DP6zd4lA5Cqyas+OoBljyRi+6EhWmFAHmRzRo7XmtHZzTb7I9/GCwB2G+kkpfh8HJMP9rtSgfk0ZRtzUsuB4xGMBNsR4TgIyEvBiro7Fa2vgWIfzrImHmg51Jg+0qkp5TlsirrCSahu/LJyyJBIyIpDrun71CB+EGYPLVF90gvIyixNWNARyoJoj+XTs2BodybXCnCTvMbvDfVmV3PlrTThPvpLnSS1FewNob/dfc1VGPMsVo6RD8joeqhC7lRYg0mhy2QLwOO2Q7A/tFH6atw4RkKQ385o/VYWbFgLhEzxS9HA4JZ7qMTlBTzFxJZc+ECEy3+k/oi4RQJd+dpDN4RdFaVe5+irVbuMS/xIp0HhL4lC/pfO/+8twQQM5xmuuy1JiGoaqe5YSYKvYVrvEpWBO3lWbdX3A52TlKoioMAgyfbGkh7m76NIO7WF31W0pv+pe/q/WT2fcLZe22vi53lyC/DXQuL3NCBaY17QniU19PXZDzgQHNkhVuRXUofNMViwWnTWrNhBmjpIoGN28tJVweIibEv9795Tk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
